apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: controller
  name: controller
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "9090"
      port: 9090
      targetPort: 9090
    - name: "9091"
      port: 9091
      targetPort: 9091
  selector:
    io.kompose.service: controller
status:
  loadBalancer: {}
