apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: controller
  name: controller
spec:
  replicas: 0
  selector:
    matchLabels:
      io.kompose.service: controller
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/fr2y-team-a-default: "true"
        io.kompose.service: controller
    spec:
      containers:
        - image: yassinemh/fr2y-team-a-controller:latest
          name: controller
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
            - containerPort: 9090
              hostPort: 9090
              protocol: TCP
            - containerPort: 9091
              hostPort: 9091
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
