apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: robot2
  name: robot2
spec:
  replicas: 0
  selector:
    matchLabels:
      io.kompose.service: robot2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/fr2y-team-a-default: "true"
        io.kompose.service: robot2
    spec:
      containers:
        - env:
            - name: INIT
              value: "0"
            - name: PORT
              value: "9092"
            - name: ROBOT_ID
              value: "2"
          image: yassinemh/fr2y-team-a-robot2:latest
          name: robot2
          resources: {}
      restartPolicy: Always
status: {}
