apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: robot4
  name: robot4
spec:
  replicas: 0
  selector:
    matchLabels:
      io.kompose.service: robot4
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/fr2y-team-a-default: "true"
        io.kompose.service: robot4
    spec:
#      initContainers:
#        - name: wait-for-controller
#          image: busybox
#          command: [ 'sh', '-c', 'until nc -w 2 -z controller 9090; do echo waiting for controller; sleep 2; done;' ]
      containers:
        - env:
            - name: INIT
              value: "0"
            - name: PORT
              value: "9094"
            - name: ROBOT_ID
              value: "4"
          image: yassinemh/fr2y-team-a-robot4:latest
          name: robot4
          resources: {}
      restartPolicy: Always
status: {}
